---
abstract: 'translating the address in Japan into kana.'
author:
  - 'Masahiro Honma  C<< <hiratara@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Install::AuthorTests: 0
  Module::Install::Repository: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-YahooJapan-KanaAddress
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  LWP::UserAgent: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hiratara/yahoojapan_kanaaddress.git
version: 0.20
